/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;

public interface RNSScreenManagerInterface<T extends View> {
  void setFullScreenSwipeEnabled(T view, boolean value);
  void setGestureEnabled(T view, boolean value);
  void setStatusBarColor(T view, @Nullable Integer value);
  void setStatusBarHidden(T view, boolean value);
  void setScreenOrientation(T view, @Nullable String value);
  void setStatusBarAnimation(T view, @Nullable String value);
  void setStatusBarStyle(T view, @Nullable String value);
  void setStatusBarTranslucent(T view, boolean value);
  void setStackPresentation(T view, @Nullable String value);
  void setStackAnimation(T view, @Nullable String value);
  void setTransitionDuration(T view, int value);
  void setReplaceAnimation(T view, @Nullable String value);
  void setNavigationBarColor(T view, @Nullable Integer value);
  void setNavigationBarHidden(T view, boolean value);
  void setNativeBackButtonDismissalEnabled(T view, boolean value);
  void setActivityState(T view, int value);
}
