/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ColorPropConverter;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;

@SuppressWarnings("deprecation")
public class RNSTabsHostManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & RNSTabsHostManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public RNSTabsHostManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "tabBarHidden":
        mViewManager.setTabBarHidden(view, value == null ? false : (boolean) value);
        break;
      case "nativeContainerBackgroundColor":
        mViewManager.setNativeContainerBackgroundColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "tabBarTintColor":
        mViewManager.setTabBarTintColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "tabBarMinimizeBehavior":
        mViewManager.setTabBarMinimizeBehavior(view, (String) value);
        break;
      case "tabBarControllerMode":
        mViewManager.setTabBarControllerMode(view, (String) value);
        break;
      case "controlNavigationStateInJS":
        mViewManager.setControlNavigationStateInJS(view, value == null ? false : (boolean) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
