/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * @generated by codegen project: GenerateModuleJniCpp.js
 */
#include "rnscreens.h"

#include <iostream>

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env;
    if (vm->GetEnv(reinterpret_cast<void **>(&env), JNI_VERSION_1_6) != JNI_OK) {
        LOG(ERROR) << "[RNScreens] error while acquiring env";
        return JNI_ERR;
    }
    return JNI_VERSION_1_6;
}

namespace facebook {
namespace react {


std::shared_ptr<TurboModule> rnscreens_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  return nullptr;
}

} // namespace react
} // namespace facebook
