
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

class JSI_EXPORT RNSScreenEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnAppear {
      
    };

  struct OnDisappear {
      
    };

  struct OnDismissed {
      int dismissCount;
    };

  struct OnNativeDismissCancelled {
      int dismissCount;
    };

  struct OnWillAppear {
      
    };

  struct OnWillDisappear {
      
    };

  struct OnTransitionProgress {
      double progress;
    int closing;
    int goingForward;
    };

  struct OnHeaderBackButtonClicked {
      
    };

  void onAppear(OnAppear value) const;

  void onDisappear(OnDisappear value) const;

  void onDismissed(OnDismissed value) const;

  void onNativeDismissCancelled(OnNativeDismissCancelled value) const;

  void onWillAppear(OnWillAppear value) const;

  void onWillDisappear(OnWillDisappear value) const;

  void onTransitionProgress(OnTransitionProgress value) const;

  void onHeaderBackButtonClicked(OnHeaderBackButtonClicked value) const;
};

} // namespace react
} // namespace facebook
