name: Test iOS SPM build

on:
  pull_request:
    branches:
      - main
      - main-labs
    paths:
      - '.github/workflows/ios-spm-build-test.yml'
      - 'Package.swift'
      - 'package.json'
      - 'react-native.config.js'
      - 'ios/**'
      - 'common/**'
      - 'cpp/**'
      - 'src/fabric/**'
  push:
    branches:
      - main
      - main-labs
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-26-xlarge
    timeout-minutes: 60
    env:
      WORKING_DIRECTORY: SPMBlankExample
    concurrency:
      group: ios-spm-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (version from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'

        # This step is required due to the bug introduced in 1.15.0 version of cocoapods
        # that breaks the pod installation for cached packages.
        # see https://github.com/facebook/react-native/issues/42698
        # This step should be removed once this issue will be resolved:
        # https://github.com/actions/runner-images/issues/9308
      - name: Install Ruby gems
        run: gem install cocoapods -v 1.15.2

      - name: Install library dependencies
        run: yarn

      - name: Prepare library
        run: yarn prepare

      - name: Pack library
        run: npm pack

      - name: Determine React Native version
        id: determine-rn-version
        run: |
          RN_VERSION=$(node -p "require('$GITHUB_WORKSPACE/package.json').devDependencies['react-native']")
          echo "Using React Native $RN_VERSION"
          echo "rn=$RN_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create blank app
        run: |
          npx @react-native-community/cli@latest init ${{ env.WORKING_DIRECTORY }} \
            --version "${{ steps.determine-rn-version.outputs.rn }}" \
            --pm npm \
            --skip-git-init

      - name: Install react-native-screens from tarball
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install "$GITHUB_WORKSPACE"/react-native-screens-*.tgz

      - name: Migrate app to Swift Package Manager
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx react-native spm add --deintegrate --yes

      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx react-native run-ios --no-packager --simulator="iPhone 17"
