name: Test iOS app
on: pull_request
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node dependencies
        run: cd TestsExample && yarn
      - name: Install pods
        run: cd TestsExample/ios && pod install
      - name: Build app
        run: cd TestsExample && yarn ios